In testframework.cpp and uninitialized.hpp as a temporary solution removed unused parameter to fix undefined reference to function linker error In throw_on_error.h and throw_on_error.hpp, overloaded a function to fix compilation error